import 'package:equatable/equatable.dart';

class BatchEntity extends Equatable {
  final String? batchId; // optional ID (can be auto-generated by Hive)
  final String batchName; // required batch name
  final String? status; // optional status: active, completed, pending

  const BatchEntity({this.batchId, required this.batchName, this.status});

  @override
  List<Object?> get props => [batchId, batchName, status];
}
